name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH  
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SERVER_IP }}
          username: ubuntu
          

            docker pull mydockerid/myapp:latest

            docker stop myapp || true
            docker rm myapp || true

            docker run -d -p 8080:8080 --name myapp mydockerid/myapp:latest
